//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public int ID { get; set; }
        public int IDNhanVien { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public int Ngay { get; set; }
        public Nullable<double> IDMucLuong { get; set; }
        public Nullable<double> SoGioLam { get; set; }
        public Nullable<bool> DanhDauChiTra { get; set; }
        public Nullable<System.DateTime> NgayChiTra { get; set; }
    }
}
